---
- name: 1. MySQL Server 설치
  dnf:
    name: mysql-server
    state: present

- name: 2. MySQL 설정 파일 배포 (Master/Slave 구분)
  template:
    src: my.cnf.j2
    dest: /etc/my.cnf
  notify: restart mysql

- name: 3. MySQL 서비스 시작
  service:
    name: mysqld
    state: started
    enabled: yes