# DB Standby Node
ansible_host: 10.2.3.3

nic_count: 1

nic1_interface: ens160
nic1_ip_address: 10.2.3.3
nic1_netmask: 255.255.255.0
nic1_gateway: 10.2.3.254
nic1_dns: 8.8.8.8

# SSH 설정은 group_vars/DB_Servers.yml에서 상속
