# FW - L3 Switch / Gateway
# Role: 172.16.6.0 <-> 10.2.1.0 routing
ansible_host: 172.16.6.61

nic_count: 2
# eth0 - External
nic1_interface: ens160
nic1_ip_address: 172.16.6.61
nic1_netmask: 255.255.255.0
nic1_gateway: 172.16.6.254
nic1_dns: 8.8.8.8

# eth1 - DMZ-1
nic2_interface: ens192
nic2_ip_address: 10.2.1.1
nic2_netmask: 255.255.255.0
# GW/DNS not needed for internal leg
